#REPLACE_VARS: ${VENDOR_REGISTRY}
FROM ${VENDOR_REGISTRY}remoteloader:idm-4.10.0-533
USER root
WORKDIR /

# fix timezone handling
RUN microdnf -y install tzdata

# Install a few useful tools
RUN microdnf -y install less vi iputils net-tools
