#REPLACE_VARS: ${VENDOR_REGISTRY}
#FROM ${VENDOR_REGISTRY}remoteloader:idm-4.10.0-533
FROM ${VENDOR_REGISTRY}remoteloader:idm-4.10.1-459
USER root
WORKDIR /

# fix timezone handling
RUN microdnf -y install tzdata

# Install a few useful tools
RUN microdnf -y install less vi iputils net-tools

# Install inotify support for better tail -f performance
RUN rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
RUN microdnf -y install inotify-tools
