#REPLACE_VARS: ${VENDOR_REGISTRY}
#FROM ${VENDOR_REGISTRY}formrenderer:idm-4.10.1-459
FROM ${VENDOR_REGISTRY}formrenderer:idm-4.10.2-591
USER root
WORKDIR /

# add server cert if available(also copy Dockerfile to prevent copy error when cert.zip does not exist)
ADD Dockerfile cert.zip* /idm/user_application/
RUN rm -f /idm/user_application/Dockerfile