#REPLACE_VARS: ${VENDOR_REGISTRY}
FROM ${VENDOR_REGISTRY}identityengine:idm-4.10.0-533
USER root
WORKDIR /

# fix timezone handling
RUN microdnf -y install tzdata

# Install a few useful tools
RUN microdnf -y install less vi iputils net-tools

# forward setup log to docker log
RUN sed -i -e '/^ *setIfVolumeConfigured *$/i tail -qFn0 /config/idm/log/idmconfigure.log 2>/dev/null &' /start.sh

